spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

write-model:
  hibernate:
    ddl-auto: create
    show-sql: true
    c3p0:
      max-size: 20
      min-size: 5
      idle-test-period: 50
      test-query: SELECT 1
  datasource:
    url: jdbc:mysql://localhost:3306/memo?useSSL=false
    username: memo
    password: memo
    name: "memo"
    initial-size: 25
    max-active: 100
    max-idle: 50
    min-idle: 25
    max-wait: 1000 # 1 second
    test-while-idle: true
    validation-query: SELECT 1
    min-evictable-idle-time-millis: 60000 # 1 minutes
    time-between-eviction-runs-millis: 5000 # 5 seconds
    max-age: 216000 #1 hour
    jmx-enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect

read-model:
  hibernate:
    ddl-auto: create
    show-sql: true
    c3p0:
      max-size: 20
      min-size: 5
      idle-test-period: 50
      test-query: SELECT 1
  datasource:
    url: jdbc:mysql://localhost:3306/memo_query?useSSL=false
    username: memo
    password: memo
    name: "memo-query"
    initial-size: 25
    max-active: 100
    max-idle: 50
    min-idle: 25
    max-wait: 1000 # 1 second
    test-while-idle: true
    validation-query: SELECT 1
    min-evictable-idle-time-millis: 60000 # 1 minutes
    time-between-eviction-runs-millis: 5000 # 5 seconds
    max-age: 216000 #1 hour
    jmx-enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
